# Generated by Django 5.0.3 on 2024-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vatStore', '0002_productdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='color',
            new_name='Season',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
