# Generated by Django 5.0.3 on 2024-05-10 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vatStore', '0005_customer_remove_order_user_remove_category_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
